#!/usr/bin/env bash
# Automatically generated by olins
# Author: @pabloskubert

# Set some bash options
set -e -o pipefail
set -f -o noglob

# Set some variables
NEED_ROOT="{need_root}"
NEED_ARGS_QTD="{qtd_args}"

# List of input args
GetVars=({vars})

# Usage message
USAGE="\nUsage: $0 ${GetVars[@]}\n"

function trap_ctrlc() {
  echo -e "\n\n Exiting script"
  exit 1
}

# Trap Ctrl+C
trap trap_ctrlc SIGINT
trap trap_ctrlc SIGTERM

# Check if the script is running as root (if needed)
if [ "$NEED_ROOT" -eq 1 ] && [ "$EUID" -ne 0 ]; then
  echo -e "\n This script must be run as root"
  exit 1
fi

# Check the number of arguments
if [ "$#" -lt "$NEED_ARGS_QTD" ]; then
  echo -e "$USAGE"
  echo -e "Command: {command_str}\n"
  exit 1
fi

# Display test message
if [ "$1" = "test" ]; then
  echo -e "\n Working!"
  exit
fi

# For each var, declare with the input arg
for inpt_arg in "${GetVars[@]}"; do
  declare "$inpt_arg"="$1"
  shift
done

command_string="{command}"

echo -e "\n Running command: $command_string \n"
eval "$command_string"

# Wait any process
wait